#!/usr/bin/env python

from OpenGL.GL import *
from OpenGL.GLU import gluPerspective
import pygame, Image
from pygame.locals import *
import manager, collector, panel, util, time

pm = manager.Manager()

def init():
	glEnable(GL_TEXTURE_2D)
	glEnable(GL_NORMALIZE)
	glEnable(GL_TEXTURE_2D)
	glEnable(GL_BLEND)
	glShadeModel(GL_SMOOTH)
	glClearColor(*util.CONST.BGCOLOR)
	glClearDepth(1.0)
	glEnable(GL_DEPTH_TEST)
	glDepthFunc(GL_LEQUAL)
	glHint(GL_PERSPECTIVE_CORRECTION_HINT, GL_NICEST)

def proj3d():
	width, height = util.CONST.VIZSIZE
	glViewport(0, 0, width, height)
	glMatrixMode(GL_PROJECTION)
	glLoadIdentity()
	gluPerspective(45, 1.0*width/height, 0.1, 500.0)
	glMatrixMode(GL_MODELVIEW)
	glLoadIdentity()

def proj2d():
	width, height = util.CONST.VIZSIZE
	glMatrixMode(GL_PROJECTION)
	glLoadIdentity()
	glOrtho(0, width, height, 0, -1, 1);
	glMatrixMode(GL_MODELVIEW)
	glLoadIdentity()

def main():
	video_flags = OPENGL|DOUBLEBUF
	pygame.init()
	surface = pygame.display.set_mode(util.CONST.VIZSIZE, video_flags)
	init()
	count, zrot, proxdir, prox = (0, 0.0, 1, -60)
	while 1:
		event = pygame.event.poll()
		if event.type == QUIT or (event.type == KEYDOWN and event.key == K_ESCAPE):
			break
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
		
		proj3d()
		# push away, and slowly rotate
		glPushMatrix()
		glTranslate(0.0, 0.0, prox)
		glRotatef(-50.0, 1.0, 0.0, 0.0)
		glRotatef(zrot, 0.0, 0.0, 1.0)
		glTranslate(-50.0, -50.0, -15.0)
		# draw 3d
		pm.draw(3)
		glPopMatrix()

		proj2d()
		# draw 2d
		pm.draw(2)

		pygame.display.flip()
		if util.CONST.SAVE_FRAMES:
			saveFrame("output/frame%05d.png" % count)
		count += 1
		#prox += proxdir/32.0
		#if prox <= util.CONST.PROXIMITY_RANGE[0] or prox >= util.CONST.PROXIMITY_RANGE[1]:
			#proxdir *= -1
		zrot += util.CONST.ROTATE_RATE
		if zrot > 360:
			zrot %= 360
		# pause
		time.sleep(util.CONST.FRAME_PAUSE)

def saveFrame(filename, format="PNG" ):
	"""Save current buffer to filename in format"""
	width, height = util.CONST.VIZSIZE
	glPixelStorei(GL_PACK_ALIGNMENT, 1)
	data = glReadPixels(0, 0, width, height, GL_RGB, GL_UNSIGNED_BYTE)
	image = Image.fromstring("RGB", (width, height), data)
	image = image.transpose(Image.FLIP_TOP_BOTTOM)
	image.save(filename, format)

if __name__ == '__main__': main()
