#!/bin/bash

if [ "${1}" = "makemov" ]
then
	 ffmpeg -sameq -i output/frame%05d.png output.avi
elif [ "${1}" = "delfiles" ]
then
	rm resources/images/*
	rm -r resources/videos/*
	find output/ -type f -name *.png -delete
	find . -name output.avi -delete
else	
	echo "makemov or delfiles"
fi
