#!/bin/bash

if [ "${1}" = "makemov" ]
then
	 ffmpeg -sameq -i output/frame%05d.png output.avi
elif [ "${1}" = "delfiles" ]
then
	rm resources/images/*
	rm -r resources/videos/*
	rm output/*
	rm output.avi
else	
	echo "makemov or delfiles"
fi
