#!/usr/bin/env python
import cairo, cStringIO
from pyglet import font, window, image

class Manager:
	def __init__(self):
		self.w, self.h = 400, 400
		self.rot = 0.04
		# pyglet
		self.win = window.Window(width=self.w, height=self.h)
		ft = font.load('Arial', 36)
		self.text = font.Text(ft, 'Hello, World!')
		# cairo
		self.surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, self.w, self.h)
		self.ctx = cairo.Context(self.surface)
		self.ctx.translate(200, 200)
	
	def draw(self):

		while not self.win.has_exit:
			# cairo
			self.ctx.rotate(self.rot)
			# clear to black
			self.ctx.set_source_rgb(0, 0, 0)
			self.ctx.paint()
			# lifted from pycairo example...
			self.ctx.set_line_width(15)
			self.ctx.set_source_rgb(255, 0, 0)
			self.ctx.move_to(0, -100)
			self.ctx.line_to(100, 100)
			self.ctx.rel_line_to(-200, 0)
			self.ctx.close_path()
			self.ctx.stroke()
			# output to file-like obj
			f = cStringIO.StringIO()
			self.surface.write_to_png(f)
			# rewind
			f.seek(0)
			# load
			self.pic = image.load('hint.png', file=f)
			#pyglet
			self.win.dispatch_events()
			self.win.clear()
			self.pic.blit(0, 0)
			self.text.draw()
			self.win.flip()

if __name__ == '__main__':
	mgr = Manager()
	mgr.draw()
